

import { ParkingSpot, Transaction, NewsItem } from './types';

// --- TARJIMALAR (DICTIONARY) ---
export const TRANSLATIONS = {
  uz: {
    slogan: "Parkovka kelajagi",
    welcome_title: "Xush kelibsiz",
    welcome_sub: "SmartParking dunyosiga kiring",
    email: "Email",
    password: "Parol",
    login_btn: "Kirish",
    admin_login: "Admin sifatida kirish",
    back: "Orqaga",
    search_placeholder: "Qayerga boramiz?",
    locate_me: "Mening joyim",
    nav_turn: "Keyingi burilish",
    nav_straight: "To'g'riga",
    nav_stop: "To'xtatish",
    price_hour: "soat",
    available: "Bo'sh joy",
    rating: "Reyting",
    navigators: "NAVIGATORLAR",
    route_btn: "Yo'l",
    book_btn: "Band qilish",
    book_title: "Joyni band qilish",
    time_hour: "VAQT (SOAT)",
    car_type: "MASHINA TURI",
    payment_method: "TO'LOV TURI",
    confirm_btn: "Tasdiqlash",
    processing: "Bajarilmoqda...",
    success_title: "Muvaffaqiyatli!",
    success_sub: "Sizning joyingiz band qilindi.",
    qr_hint: "Kirishda shu QR kodni ko'rsating",
    back_map: "Xaritaga qaytish",
    my_garage: "Mening Garajim",
    add_car: "Yangi mashina qo'shish",
    car_added: "Mashina qo'shildi",
    car_removed: "Mashina o'chirildi",
    wallet: "Hamyon",
    current_balance: "Joriy Balans",
    top_up: "Hisobni to'ldirish (+50k)",
    history: "Tarix",
    favorites: "Sevimli Parkovkalar",
    no_favorites: "Hozircha sevimli joylar yo'q",
    driver: "Haydovchi",
    admin: "Administrator",
    bonus: "Bonus",
    install_app: "Ilovani O'rnatish",
    my_cars: "Mening mashinalarim",
    payments: "To'lovlar tarixi",
    fav_spots: "Sevimli parkovkalar",
    lang_select: "Til: O'zbek",
    logout: "Chiqish",
    admin_panel: "Admin Panel",
    weather: "Toshkent",
    // WEATHER CONDITIONS
    w_sunny: "Quyoshli",
    w_clear: "Ochiq havo",
    w_cloudy: "Bulutli",
    w_rain: "Yomg'ir",
    w_snow: "Qor",
    w_thunder: "Momaqaldiroq",
    w_fog: "Tuman",
    w_drizzle: "Yog'ingarchilik",
    // PARKING TIPS
    tip_rain: "Yopiq parkovka tavsiya etiladi",
    tip_hot: "Soya joy qidiring",
    tip_nice: "Ob-havo ajoyib!",
    
    toast_login: "Tizimga kirildi",
    toast_route: "Marshrut chizilmoqda...",
    toast_fav_add: "Sevimlilarga qo'shildi",
    toast_fav_remove: "Sevimlilardan olib tashlandi",
    toast_booked: "Muvaffaqiyatli band qilindi!",
    toast_topup: "Hisob to'ldirildi",
    toast_error: "Xatolik yuz berdi",
    small: "Kichik",
    sedan: "Sedan",
    crossover: "Krossover",
    large: "Katta",
    total: "Jami summa",
    about_title: "Parkovkani\nAqlli Toping",
    about_desc: "Shahardagi eng qulay joylarni toping, band qiling va vaqtingizni tejang.",
    start_btn: "Boshlash",
    fast: "Tezkor",
    secure: "Xavfsiz",
    version: "Versiya",
    help: "Yordam",
    report_btn: "Xabar berish",
    report_title: "Muammo haqida xabar",
    issue_full: "Aslida joy yo'q",
    issue_price: "Narx noto'g'ri",
    issue_closed: "Parkovka yopiq",
    report_sent: "Xabar yuborildi!",
    find_my_car: "Mashinam qayerda?",
    mark_car: "Shu yerga qo'ydim",
    car_saved: "Mashina joylashuvi saqlandi!",
    nav_to_car: "Mashinaga borish",
    remove_marker: "O'chirish",
    achievements: "Yutuqlar",
    level: "Daraja",
    novice: "Havaskor",
    expert: "Professional",
    master: "Afsona",
    ach_1: "Birinchi Qadam",
    ach_1_desc: "Ilk marotaba parkovka qildingiz",
    ach_2: "Eco Do'st",
    ach_2_desc: "Elektr mashina quvvatladingiz",
    ach_3: "Tungi Poygachi",
    ach_3_desc: "Tunda parkovka qildingiz",
    ach_4: "Sodiq Mijoz",
    ach_4_desc: "5 marta xizmatdan foydalandingiz",
    car_here: "Mashina shu yerda",
    gps_error: "GPS topilmadi, xarita markazi olindi",
    scan_title: "QR Skaner",
    scan_desc: "Kirish yoki chiqish uchun kamerani QR kodga yo'naltiring",
    scan_success: "Muvaffaqiyatli!",
    news_title: "Yangiliklar & Chegirmalar",
    news_promo: "AKSIYA",
    news_alert: "OGOHLANTIRISH",
    news_info: "XABAR",
    // --- SUPPORT ---
    support_title: "Texnik Yordam",
    support_desc: "Yo'lda qoldingizmi? Biz yordam beramiz!",
    srv_tow: "Evakuator",
    srv_tire: "G'ildirak almashtirish",
    srv_fuel: "Benzin yetkazish",
    srv_jump: "Akkumulyator (Prikurka)",
    srv_lock: "Qulf ochish ustasi",
    call_now: "Chaqirish",
    calling_service: "Xizmat qidirilmoqda...",
    service_requested: "Buyurtma qabul qilindi! Usta siz bilan bog'lanadi.",
    // --- VISUAL SELECTION & VOICE ---
    select_spot_title: "Joyni tanlang",
    floor: "Qavat",
    spot: "Joy",
    entrance: "Kirish",
    nav_started_voice: "Marshrut boshlandi. Ehtiyot bo'ling.",
    nav_arrived_voice: "Manzilga yetib keldingiz.",
  },
  ru: {
    slogan: "Будущее парковки",
    welcome_title: "Добро пожаловать",
    welcome_sub: "Войдите в мир SmartParking",
    email: "Эл. адрес",
    password: "Пароль",
    login_btn: "Войти",
    admin_login: "Войти как Админ",
    back: "Назад",
    search_placeholder: "Куда поедем?",
    locate_me: "Где я",
    nav_turn: "Следующий поворот",
    nav_straight: "Прямо",
    nav_stop: "Остановить",
    price_hour: "час",
    available: "Свободно",
    rating: "Рейтинг",
    navigators: "НАВИГАТОРЫ",
    route_btn: "Маршрут",
    book_btn: "Бронь",
    book_title: "Бронирование места",
    time_hour: "ВРЕМЯ (ЧАС)",
    car_type: "ТИП МАШИНЫ",
    payment_method: "СПОСОБ ОПЛАТЫ",
    confirm_btn: "Подтвердить",
    processing: "Обработка...",
    success_title: "Успешно!",
    success_sub: "Ваше место забронировано.",
    qr_hint: "Покажите этот QR код на въезде",
    back_map: "На карту",
    my_garage: "Мой Гараж",
    add_car: "Добавить машину",
    car_added: "Машина добавлена",
    car_removed: "Машина удалена",
    wallet: "Кошелек",
    current_balance: "Текущий баланс",
    top_up: "Пополнить (+50k)",
    history: "История",
    favorites: "Избранные парковки",
    no_favorites: "Пока нет избранных мест",
    driver: "Водитель",
    admin: "Администратор",
    bonus: "Бонус",
    install_app: "Установить приложение",
    my_cars: "Мои машины",
    payments: "История оплат",
    fav_spots: "Избранное",
    lang_select: "Язык: Русский",
    logout: "Выйти",
    admin_panel: "Админ панель",
    weather: "Ташкент",
    w_sunny: "Солнечно",
    w_clear: "Ясно",
    w_cloudy: "Облачно",
    w_rain: "Дождь",
    w_snow: "Снег",
    w_thunder: "Гроза",
    w_fog: "Туман",
    w_drizzle: "Морось",
    tip_rain: "Рекомендуем крытую парковку",
    tip_hot: "Ищите место в тени",
    tip_nice: "Погода отличная!",
    
    toast_login: "Вход выполнен",
    toast_route: "Маршрут построен...",
    toast_fav_add: "Добавлено в избранное",
    toast_fav_remove: "Удалено из избранного",
    toast_booked: "Успешно забронировано!",
    toast_topup: "Баланс пополнен",
    toast_error: "Произошла ошибка",
    small: "Мини",
    sedan: "Седан",
    crossover: "Кроссовер",
    large: "Джип",
    total: "Итого",
    about_title: "Парковка\nс Умом",
    about_desc: "Найдите лучшие места в городе, бронируйте и экономьте время.",
    start_btn: "Начать",
    fast: "Быстро",
    secure: "Безопасно",
    version: "Версия",
    help: "Помощь",
    report_btn: "Сообщить",
    report_title: "Сообщить о проблеме",
    issue_full: "Мест нет (Ошибка)",
    issue_price: "Неверная цена",
    issue_closed: "Парковка закрыта",
    report_sent: "Сообщение отправлено!",
    find_my_car: "Где моя машина?",
    mark_car: "Припарковать здесь",
    car_saved: "Местоположение сохранено!",
    nav_to_car: "К машине",
    remove_marker: "Удалить",
    achievements: "Достижения",
    level: "Уровень",
    novice: "Новичок",
    expert: "Профи",
    master: "Легенда",
    ach_1: "Первый шаг",
    ach_1_desc: "Первая парковка",
    ach_2: "Эко Друг",
    ach_2_desc: "Зарядка электромобиля",
    ach_3: "Ночной гонщик",
    ach_3_desc: "Ночная парковка",
    ach_4: "Верный клиент",
    ach_4_desc: "5 использований сервиса",
    car_here: "Машина здесь",
    gps_error: "GPS не найден, взят центр карты",
    scan_title: "QR Сканер",
    scan_desc: "Наведите камеру на QR код для въезда или выезда",
    scan_success: "Успешно!",
    news_title: "Новости и Скидки",
    news_promo: "АКЦИЯ",
    news_alert: "ВНИМАНИЕ",
    news_info: "НОВОСТЬ",
    // --- SUPPORT ---
    support_title: "Техпомощь",
    support_desc: "Случилась беда? Мы поможем!",
    srv_tow: "Эвакуатор",
    srv_tire: "Замена колеса",
    srv_fuel: "Доставка бензина",
    srv_jump: "Прикурить АКБ",
    srv_lock: "Вскрытие замков",
    call_now: "Вызвать",
    calling_service: "Поиск службы...",
    service_requested: "Заказ принят! Мастер свяжется с вами.",
    // --- VISUAL SELECTION & VOICE ---
    select_spot_title: "Выберите место",
    floor: "Этаж",
    spot: "Место",
    entrance: "Въезд",
    nav_started_voice: "Маршрут построен. Будьте осторожны.",
    nav_arrived_voice: "Вы прибыли в пункт назначения.",
  },
  cyr: {
    slogan: "Парковка келажаги",
    welcome_title: "Хуш келибсиз",
    welcome_sub: "SmartParking дунёсига киринг",
    email: "Email",
    password: "Пароль",
    login_btn: "Кириш",
    admin_login: "Админ сифатида кириш",
    back: "Орқага",
    search_placeholder: "Қаерга борамиз?",
    locate_me: "Менинг жойим",
    nav_turn: "Кейинги бурилиш",
    nav_straight: "Тўғрига",
    nav_stop: "Тўхтатиш",
    price_hour: "соат",
    available: "Бўш жой",
    rating: "Рейтинг",
    navigators: "НАВИГАТОРЛАР",
    route_btn: "Йўл",
    book_btn: "Банд қилиш",
    book_title: "Жойни банд қилиш",
    time_hour: "ВАҚТ (СОАТ)",
    car_type: "МАШИНА ТУРИ",
    payment_method: "ТЎЛОВ ТУРИ",
    confirm_btn: "Тасдиқлаш",
    processing: "Бажарилмоқда...",
    success_title: "Муваффақиятли!",
    success_sub: "Сизнинг жойингиз банд қилинди.",
    qr_hint: "Киришда шу QR кодни кўрсатинг",
    back_map: "Харитага қайтиш",
    my_garage: "Менинг Гаражим",
    add_car: "Янги машина қўшиш",
    car_added: "Машина қўшилди",
    car_removed: "Машина ўчирилди",
    wallet: "Ҳамён",
    current_balance: "Жорий Баланс",
    top_up: "Ҳисобни тўлдириш (+50k)",
    history: "Тарих",
    favorites: "Севимли Парковкалар",
    no_favorites: "Ҳозирча севимли жойлар йўқ",
    driver: "Ҳайдовчи",
    admin: "Администратор",
    bonus: "Бонус",
    install_app: "Иловани Ўрнатиш",
    my_cars: "Менинг машиналарим",
    payments: "Тўловлар тарихи",
    fav_spots: "Севимли парковкалар",
    lang_select: "Тил: Ўзбекча",
    logout: "Чиқиш",
    admin_panel: "Админ Панел",
    weather: "Тошкент",
    w_sunny: "Қуёшли",
    w_clear: "Очиқ ҳаво",
    w_cloudy: "Булутли",
    w_rain: "Ёмғир",
    w_snow: "Қор",
    w_thunder: "Момақалдироқ",
    w_fog: "Туман",
    w_drizzle: "Ёғингарчилик",
    tip_rain: "Ёпиқ парковка тавсия этилади",
    tip_hot: "Соя жой қидиринг",
    tip_nice: "Об-ҳаво ажойиб!",

    toast_login: "Тизимга кирилди",
    toast_route: "Маршрут чизилмоқда...",
    toast_fav_add: "Севимлиларга қўшилди",
    toast_fav_remove: "Севимлилардан олиб ташланди",
    toast_booked: "Муваффақиятли банд қилинди!",
    toast_topup: "Ҳисоб тўлдирилди",
    toast_error: "Хатолик юз берди",
    small: "Кичик",
    sedan: "Седан",
    crossover: "Кроссовер",
    large: "Катта",
    total: "Жами сумма",
    about_title: "Парковкани\nАқлли Топинг",
    about_desc: "Шаҳардаги энг қулай жойларни топинг, банд қилинг ва вақтингизни тежанг.",
    start_btn: "Бошлаш",
    fast: "Тезкор",
    secure: "Хавфсиз",
    version: "Версия",
    help: "Ёрдам",
    report_btn: "Хабар бериш",
    report_title: "Муаммо ҳақида хабар",
    issue_full: "Аслида жой йўқ",
    issue_price: "Нарх нотўғри",
    issue_closed: "Парковка ёпиқ",
    report_sent: "Хабар юборилди!",
    find_my_car: "Машинам қаерда?",
    mark_car: "Шу ерга қўйдим",
    car_saved: "Машина жойлашуви сақланди!",
    nav_to_car: "Машинага бориш",
    remove_marker: "Ўчириш",
    achievements: "Ютуқлар",
    level: "Даража",
    novice: "Ҳаваскор",
    expert: "Профессионал",
    master: "Афсона",
    ach_1: "Биринчи Қадам",
    ach_1_desc: "Илк маротаба парковка қилдингиз",
    ach_2: "Эко Дўст",
    ach_2_desc: "Электр машина қувватладингиз",
    ach_3: "Тунги Пойгачи",
    ach_3_desc: "Тунда парковка қилдингиз",
    ach_4: "Содиқ Мижоз",
    ach_4_desc: "5 марта хизматдан фойдаландингиз",
    car_here: "Машина шу ерда",
    gps_error: "GPS топилмади, харита маркази олинди",
    scan_title: "QR Сканер",
    scan_desc: "Кириш ёки чиқиш учун камерани QR кодга йўналтиринг",
    scan_success: "Муваффақиятли!",
    news_title: "Янгиликлар ва Чегирмалар",
    news_promo: "АКЦИЯ",
    news_alert: "ОГОҲЛАНТИРИШ",
    news_info: "ХАБАР",
    // --- SUPPORT ---
    support_title: "Техник Ёрдам",
    support_desc: "Йўлда қолдингизми? Биз ёрдам берамиз!",
    srv_tow: "Эвакуатор",
    srv_tire: "Ғилдирак алмаштириш",
    srv_fuel: "Benzin yetkazish",
    srv_jump: "Аккумулятор (Прикурка)",
    srv_lock: "Қулф очиш устаси",
    call_now: "Чақириш",
    calling_service: "Хизмат қидирилмоқда...",
    service_requested: "Буюртма қабул қилинди! Уста сиз билан боғланади.",
    // --- VISUAL SELECTION & VOICE ---
    select_spot_title: "Жойни танланг",
    floor: "Қават",
    spot: "Жой",
    entrance: "Кириш",
    nav_started_voice: "Маршрут бошланди. Эҳтиёт бўлинг.",
    nav_arrived_voice: "Манзилга етиб келдингиз.",
  }
};

// Mock Data for Parking Spots in Tashkent (Real Coordinates & More Spots)
export const MOCK_PARKING_SPOTS: ParkingSpot[] = [
  // --- MARKAZ (CENTER) ---
  {
    id: '1',
    name: 'Chorsu Market (Eski Juva)',
    address: 'Beruniy Street',
    lat: 41.3283, // Precise entry
    lng: 69.2389,
    type: 'standard',
    totalSpots: 120,
    availableSpots: 12,
    basePricePerHour: 5000,
    rating: 4.5,
    image: 'https://picsum.photos/400/200?random=1',
    features: ['Camera', 'Yoritish', 'Qorovul'],
    is247: true,
  },
  {
    id: '2',
    name: 'Tashkent City Mall (Underground)',
    address: 'Furqat Street',
    lat: 41.3135,
    lng: 69.2588,
    type: 'ev',
    totalSpots: 500,
    availableSpots: 210,
    basePricePerHour: 10000,
    rating: 4.8,
    image: 'https://picsum.photos/400/200?random=2',
    features: ['Quvvatlash', 'Yuvish', 'Avtomat'],
    is247: true,
  },
  {
    id: '3',
    name: 'Magic City (Aquarium)',
    address: 'Bobur Street',
    lat: 41.3045, 
    lng: 69.2482,
    type: 'standard',
    totalSpots: 300,
    availableSpots: 45,
    basePricePerHour: 8000,
    rating: 4.7,
    image: 'https://picsum.photos/400/200?random=3',
    features: ['Oila uchun', 'Keng'],
    is247: true,
  },
  {
    id: '4',
    name: 'Humo Arena Parking',
    address: 'Beshyog\'och Street',
    lat: 41.3005,
    lng: 69.2452,
    type: 'standard',
    totalSpots: 400,
    availableSpots: 350, // Usually empty on non-event days
    basePricePerHour: 5000,
    rating: 4.6,
    image: 'https://picsum.photos/400/200?random=4',
    features: ['Keng', 'Tadbirlar'],
    is247: false,
  },
  {
    id: '5',
    name: 'Hyatt Regency / Library',
    address: 'Navoi Street',
    lat: 41.3148,
    lng: 69.2745,
    type: 'standard',
    totalSpots: 80,
    availableSpots: 5,
    basePricePerHour: 15000,
    rating: 4.9,
    image: 'https://picsum.photos/400/200?random=5',
    features: ['Premium', 'Valet'],
    is247: true,
  },
  {
    id: '6',
    name: 'Amir Temur Square (Broadway)',
    address: 'Sayilgoh Street',
    lat: 41.3105,
    lng: 69.2798,
    type: 'standard',
    totalSpots: 40,
    availableSpots: 2,
    basePricePerHour: 10000,
    rating: 4.4,
    image: 'https://picsum.photos/400/200?random=6',
    features: ['Markaz', 'Tirband'],
    is247: false,
  },
  {
    id: '7',
    name: 'TSUM (Cosmonauts)',
    address: 'Sharaf Rashidov Avenue',
    lat: 41.3095,
    lng: 69.2710,
    type: 'standard',
    totalSpots: 60,
    availableSpots: 10,
    basePricePerHour: 8000,
    rating: 4.3,
    image: 'https://picsum.photos/400/200?random=7',
    features: ['Savdo', 'Ofislar'],
    is247: true,
  },

  // --- BOZORLAR & SAVDO (MARKETS & MALLS) ---
  {
    id: '8',
    name: 'Oloy Bozori (Main)',
    address: 'Amir Temur Avenue',
    lat: 41.3195,
    lng: 69.2825,
    type: 'standard',
    totalSpots: 150,
    availableSpots: 20,
    basePricePerHour: 4000,
    rating: 4.2,
    image: 'https://picsum.photos/400/200?random=8',
    features: ['Bozor', 'Arzon'],
    is247: true,
  },
  {
    id: '9',
    name: 'Malika Texnika Bozori',
    address: 'Kichik Halqa Yo\'li',
    lat: 41.3415,
    lng: 69.2645,
    type: 'standard',
    totalSpots: 200,
    availableSpots: 0, // Often full
    basePricePerHour: 5000,
    rating: 4.0,
    image: 'https://picsum.photos/400/200?random=9',
    features: ['Texnika', 'Tirband'],
    is247: true,
  },
  {
    id: '10',
    name: 'Samarqand Darvoza',
    address: 'Qoratosh Street',
    lat: 41.3162,
    lng: 69.2315,
    type: 'ev',
    totalSpots: 180,
    availableSpots: 45,
    basePricePerHour: 5000,
    rating: 4.6,
    image: 'https://picsum.photos/400/200?random=10',
    features: ['Quvvatlash', 'Savdo', 'Kino'],
    is247: true,
  },
  {
    id: '11',
    name: 'Riviera Mall',
    address: 'Sebzor Street',
    lat: 41.3365,
    lng: 69.2458,
    type: 'standard',
    totalSpots: 120,
    availableSpots: 60,
    basePricePerHour: 6000,
    rating: 4.7,
    image: 'https://picsum.photos/400/200?random=11',
    features: ['Muz saroyi', 'Teras'],
    is247: true,
  },
  {
    id: '12',
    name: 'Mega Planet',
    address: 'Ahmad Donish Street',
    lat: 41.3665,
    lng: 69.2905,
    type: 'standard',
    totalSpots: 150,
    availableSpots: 75,
    basePricePerHour: 3000,
    rating: 4.3,
    image: 'https://picsum.photos/400/200?random=12',
    features: ['Yunusobod', 'Bozor'],
    is247: true,
  },
  {
    id: '13',
    name: 'Next Mall',
    address: 'Bobur Street',
    lat: 41.2945,
    lng: 69.2505,
    type: 'standard',
    totalSpots: 120,
    availableSpots: 15,
    basePricePerHour: 5000,
    rating: 4.5,
    image: 'https://picsum.photos/400/200?random=13',
    features: ['Kino', 'Muzqaymoq'],
    is247: true,
  },
  {
    id: '14',
    name: 'Compass Mall',
    address: 'Farg\'ona Yo\'li',
    lat: 41.2395,
    lng: 69.3365,
    type: 'standard',
    totalSpots: 350,
    availableSpots: 200,
    basePricePerHour: 2000,
    rating: 4.4,
    image: 'https://picsum.photos/400/200?random=14',
    features: ['Qo\'yliq', 'Metro'],
    is247: true,
  },
  {
    id: '15',
    name: 'Atlas Chilonzor',
    address: 'Qatortol Street',
    lat: 41.2825,
    lng: 69.2045,
    type: 'standard',
    totalSpots: 100,
    availableSpots: 40,
    basePricePerHour: 3000,
    rating: 4.2,
    image: 'https://picsum.photos/400/200?random=15',
    features: ['Mebel', 'Arzon'],
    is247: true,
  },
  {
    id: '16',
    name: 'Depo Mall',
    address: 'Lutfiy Street',
    lat: 41.2865,
    lng: 69.1855,
    type: 'standard',
    totalSpots: 80,
    availableSpots: 20,
    basePricePerHour: 4000,
    rating: 4.1,
    image: 'https://picsum.photos/400/200?random=16',
    features: ['Savdo', 'Ovqat'],
    is247: true,
  },

  // --- TRANSPORT HUBS ---
  {
    id: '17',
    name: 'Toshkent Xalqaro Aeroporti (Dep)',
    address: 'Aeroport Yo\'li',
    lat: 41.2635,
    lng: 69.2685,
    type: 'standard',
    totalSpots: 600,
    availableSpots: 150,
    basePricePerHour: 20000,
    rating: 4.3,
    image: 'https://picsum.photos/400/200?random=17',
    features: ['Uzoq muddat', 'Qimmat'],
    is247: true,
  },
  {
    id: '18',
    name: 'Shimoliy Vokzal (Severniy)',
    address: 'Turkiston Street',
    lat: 41.2935,
    lng: 69.2885,
    type: 'standard',
    totalSpots: 100,
    availableSpots: 10,
    basePricePerHour: 8000,
    rating: 4.0,
    image: 'https://picsum.photos/400/200?random=18',
    features: ['Kutish zali', 'Taxi'],
    is247: true,
  },

  // --- PARKS & OTHERS ---
  {
    id: '19',
    name: 'Eco Park',
    address: 'Mahtumquli Street',
    lat: 41.3045,
    lng: 69.2948,
    type: 'ev',
    totalSpots: 40,
    availableSpots: 8,
    basePricePerHour: 6000,
    rating: 4.8,
    image: 'https://picsum.photos/400/200?random=19',
    features: ['Sport', 'EV Station'],
    is247: true,
  },
  {
    id: '20',
    name: 'Minor Masjidi',
    address: 'Kichik Halqa Yo\'li',
    lat: 41.3285,
    lng: 69.2785,
    type: 'standard',
    totalSpots: 70,
    availableSpots: 65,
    basePricePerHour: 2000,
    rating: 4.9,
    image: 'https://picsum.photos/400/200?random=20',
    features: ['Tinch', 'Manzara'],
    is247: true,
  },
  {
    id: '21',
    name: 'TV Tower (Teleminora)',
    address: 'Amir Temur Avenue',
    lat: 41.3455,
    lng: 69.2845,
    type: 'standard',
    totalSpots: 50,
    availableSpots: 20,
    basePricePerHour: 5000,
    rating: 4.5,
    image: 'https://picsum.photos/400/200?random=21',
    features: ['Turizm', 'Osh markazi'],
    is247: true,
  },
  {
    id: '22',
    name: 'Bunyodkor Stadioni',
    address: 'Bunyodkor Avenue',
    lat: 41.2815,
    lng: 69.2135,
    type: 'standard',
    totalSpots: 400,
    availableSpots: 380, // Empty on non-match days
    basePricePerHour: 3000,
    rating: 4.6,
    image: 'https://picsum.photos/400/200?random=22',
    features: ['Sport', 'Keng'],
    is247: true,
  },
  {
    id: '23',
    name: 'Sergeli Mashina Bozori',
    address: 'Yangisergeli Street',
    lat: 41.2055,
    lng: 69.2205,
    type: 'standard',
    totalSpots: 1000,
    availableSpots: 100, // Busy on weekends
    basePricePerHour: 10000,
    rating: 3.8,
    image: 'https://picsum.photos/400/200?random=23',
    features: ['Savdo', 'Tirband'],
    is247: false,
  },
  {
    id: '24',
    name: 'Ashxobod Sayilgohi',
    address: 'Mahtumquli Street',
    lat: 41.3025,
    lng: 69.3105,
    type: 'standard',
    totalSpots: 200,
    availableSpots: 50,
    basePricePerHour: 5000,
    rating: 4.4,
    image: 'https://picsum.photos/400/200?random=24',
    features: ['Attraksion', 'Oila'],
    is247: true,
  },
  {
    id: '25',
    name: 'Parkent Bozori',
    address: 'Parkent Street',
    lat: 41.3155,
    lng: 69.3255,
    type: 'standard',
    totalSpots: 80,
    availableSpots: 10,
    basePricePerHour: 3000,
    rating: 4.1,
    image: 'https://picsum.photos/400/200?random=25',
    features: ['Bozor', 'Arzon'],
    is247: true,
  },
];

export const CAR_TYPES = [
  { id: 'small', labelKey: 'small', desc: 'Matiz/Spark', multiplier: 1 },
  { id: 'sedan', labelKey: 'sedan', desc: 'Cobalt/Gentra', multiplier: 1.1 },
  { id: 'crossover', labelKey: 'crossover', desc: 'Tracker', multiplier: 1.2 },
  { id: 'large', labelKey: 'large', desc: 'Tahoe/Prado', multiplier: 1.4 },
];

export const PAYMENT_METHODS = [
  { id: 'payme', label: 'Payme', icon: 'credit-card' },
  { id: 'click', label: 'Click', icon: 'smartphone' },
  { id: 'card', label: 'Karta', icon: 'credit-card' },
  { id: 'card', label: 'Naqd', icon: 'banknote' },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', type: 'deposit', amount: 50000, date: '2023-10-25T10:00:00Z', description: 'Click' },
  { id: 't2', type: 'payment', amount: 15000, date: '2023-10-24T14:30:00Z', description: 'Chorsu Market Parking' },
  { id: 't3', type: 'payment', amount: 8000, date: '2023-10-23T09:15:00Z', description: 'EcoPark EV Station' },
];

export const MOCK_ADMIN_STATS = [
  { name: 'Mon', revenue: 4000, users: 240 },
  { name: 'Tue', revenue: 3000, users: 139 },
  { name: 'Wed', revenue: 2000, users: 980 },
  { name: 'Thu', revenue: 2780, users: 390 },
  { name: 'Fri', revenue: 1890, users: 480 },
  { name: 'Sat', revenue: 2390, users: 380 },
  { name: 'Sun', revenue: 3490, users: 430 },
];

export const MOCK_NEWS: NewsItem[] = [
  { 
    id: 'n1', 
    title: 'Mustaqillik ko\'chasida ta\'mirlash', 
    desc: 'Diqqat! 25-oktabrgacha yo\'l qisman yopiq bo\'ladi. Aylanma yo\'llardan foydalaning.', 
    date: '2023-10-24', 
    image: 'https://picsum.photos/400/200?random=20', 
    type: 'alert' 
  },
  { 
    id: 'n2', 
    title: 'Tashkent City -50% Chegirma', 
    desc: 'Dam olish kunlari parkovka narxiga 50% chegirma e\'lon qilindi! Shoshiling.', 
    date: '2023-10-25', 
    image: 'https://picsum.photos/400/200?random=21', 
    type: 'promo' 
  },
  { 
    id: 'n3', 
    title: 'Yomg\'irli ob-havo kutilmoqda', 
    desc: 'Ertaga kuchli yomg\'ir yog\'ishi kutilmoqda. Yopiq parkovkalardan foydalanishni tavsiya qilamiz.', 
    date: '2023-10-26', 
    image: 'https://picsum.photos/400/200?random=22', 
    type: 'info' 
  }
];